-- 코드를 작성해주세요
SELECT count(*) as FISH_COUNT
FROM FISH_INFO as F
    JOIN FISH_NAME_INFO as N
    ON F.FISH_TYPE = N.FISH_TYPE
WHERE N.FISH_NAME = 'BASS' or N.FISH_NAME = 'SNAPPER'

# SELECT count(*) as FISH_COUNT
# FROM FISH_INFO
# WHERE FISH_TYPE = 0 or FISH_TYPE = 1